### ISSUE TITLE
hey zarcolio  i have problem with this can you fixe it 

### ISSUE THREAD

**Issue by dragonblack4942** [Zarcolio/sitedorks#3]
![image](https://user-images.githubusercontent.com/105872434/183642547-29e76a78-823f-45d1-89c4-8d86d8a1f577.png)       sorry about the resolution    photo i take the photo from my handphone   any way thanks for the tool stay safe zarcolio

**Comment by Zarcolio** [comment]
Hi dragonblack4942, sorry to hear you're having issues.
Can you tell me which OS and which shell you're using?

**Comment by dragonblack4942** [comment]
im using kali version 2022.2 gui xfce


Pada tanggal Sel, 9 Agt 2022 19:14, Zarcolio ***@***.***>
menulis:

**Comment by Zarcolio** [comment]
Hey again, I think I fixed it.
Try the new install script :)

**Comment by dragonblack4942** [comment]
how i install new script

**Comment by Zarcolio** [comment]
git pull origin main

☺️

**Comment by Zarcolio** [comment]
Good luck in Indonesia 🙏💪
Let me me know if it works 😊
